
# MySQL ??

spring:
  datasource:
    url: jdbc:mysql://3.39.214.207:3306/umc_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: dbdpaTl12!
    driver-class-name: com.mysql.cj.jdbc.Driver